In [31]:
import json

import pandas as pd

In [19]:
with open(r'C:\Users\cmullins\Desktop\ksi\site_adts.txt') as f:
    site_adts_df = json.loads(f.read())

with open(r'C:\Users\cmullins\Desktop\ksi\site_locs.txt') as f:
    site_locs_df = json.loads(f.read())

In [54]:
site_adts = pd.DataFrame(site_adts_df['data'])
site_locs = pd.DataFrame(site_locs_df['data']).T.reset_index(drop=True)

In [55]:
df = pd.merge(site_adts, site_locs, left_on='siteId', right_on='id')
df.head()

,siteId,year,coverage,totalCount,speedAvg,speed85Pct,hgvPml,aadt,aadtMethod,id,...,isDisabled,collectionInterval,speedLimit,bearing,location,parameters,siteParameters,nodeParameters,sysParameters,tz
0,0004D4E4-35C9-4478-B6BB-60ADA9849F25,2011,0.774,22727,NaN,NaN,0.0,80.0,weekday5Plus2,0004D4E4-35C9-4478-B6BB-60ADA9849F25,...,False,0,13411,330,"{'lat': 52.68116, 'lng': -1.10999}","{'tz': 'Europe/London', 'hz': 'GB.ENG', 'enabl...",{},{},"{'tz': 'Europe/London', 'hz': 'GB.ENG', 'enabl...",Europe/London
1,0004D4E4-35C9-4478-B6BB-60ADA9849F25,2012,0.452,9887,NaN,NaN,0.0,56.0,weekday5Plus2,0004D4E4-35C9-4478-B6BB-60ADA9849F25,...,False,0,13411,330,"{'lat': 52.68116, 'lng': -1.10999}","{'tz': 'Europe/London', 'hz': 'GB.ENG', 'enabl...",{},{},"{'tz': 'Europe/London', 'hz': 'GB.ENG', 'enabl...",Europe/London
2,0004D4E4-35C9-4478-B6BB-60ADA9849F25,2013,0.000,0,NaN,NaN,NaN,56.0,weekday5Plus2,0004D4E4-35C9-4478-B6BB-60ADA9849F25,...,False,0,13411,330,"{'lat': 52.68116, 'lng': -1.10999}","{'tz': 'Europe/London', 'hz': 'GB.ENG', 'enabl...",{},{},"{'tz': 'Europe/London', 'hz': 'GB.ENG', 'enabl...",Europe/London
3,0004D4E4-35C9-4478-B6BB-60ADA9849F25,2014,0.000,0,NaN,NaN,NaN,38.0,weekday5Plus2,0004D4E4-35C9-4478-B6BB-60ADA9849F25,...,False,0,13411,330,"{'lat': 52.68116, 'lng': -1.10999}","{'tz': 'Europe/London', 'hz': 'GB.ENG', 'enabl...",{},{},"{'tz': 'Europe/London', 'hz': 'GB.ENG', 'enabl...",Europe/London
4,0004D4E4-35C9-4478-B6BB-60ADA9849F25,2015,0.000,0,NaN,NaN,NaN,22.0,weekday5Plus2,0004D4E4-35C9-4478-B6BB-60ADA9849F25,...,False,0,13411,330,"{'lat': 52.68116, 'lng': -1.10999}","{'tz': 'Europe/London', 'hz': 'GB.ENG', 'enabl...",{},{},"{'tz': 'Europe/London', 'hz': 'GB.ENG', 'enabl...",Europe/London

In [56]:
locs = df['location'].apply(lambda x: pd.Series(x))

In [57]:
df = pd.concat([df, locs], axis=1)
df = df.filter([
    'siteId',
    'node',
    'cosit',
    'description',
    'year',
    'aadt',
    'lat',
    'lng'
])

In [64]:
df['hyperlink'] = 'https://drakewell02.drakewell.com/calendar_alt.asp?node=' + df['node'] + '&cosit=' + df['cosit']

In [68]:
df.dropna(subset='aadt') \
    .to_csv('site_adts.csv', index=False)